/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IHeroiconsBars3: typeof import('~icons/heroicons/bars3')['default']
    IHeroiconsBars3Solid: typeof import('~icons/heroicons/bars3-solid')['default']
    IHeroiconsXMark: typeof import('~icons/heroicons/x-mark')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
